package main

import (
	"fmt"
	"github.com/elden43/aoc2022/solutions/day15"
)

func main() {
	fmt.Println("Advent GO Code 2022")
	fmt.Println("-------------------")
	//fmt.Println("Day1")
	//solutions.Day1part1()
	//solutions.Day1part2()
	//fmt.Println("Day2")
	//solutions.Day2part1()
	//solutions.Day2part2()
	//fmt.Println("Day3")
	//solutions.Day3part1()
	//solutions.Day3part2()
	//fmt.Println("Day4")
	//solutions.Day4part1()
	//solutions.Day4part2()
	//fmt.Println("Day5")
	//solutions.Day5part1()
	//solutions.Day5part2()
	//fmt.Println("Day6")
	//solutions.Day6part1()
	//solutions.Day6part2()
	//fmt.Println("Day7")
	//solutions.Day7part1()
	//solutions.Day7part2()
	//fmt.Println("Day8")
	//solutions.Day8part1()
	//solutions.Day8part2()
	//fmt.Println("Day9")
	//solutions.Day9part1()
	//solutions.Day9part2()
	//fmt.Println("Day10")
	//solutions.Day10part1()
	//solutions.Day10part2()
	//fmt.Println("Day11")
	//solutions.Day11part1()
	//solutions.Day11part2()
	//fmt.Println("Day13")
	//solutions.Day13part1()
	//solutions.Day13part2()
	//solutions.Helpme()
	//day14.Part1()
	//day14.Part2()
	day15.Part1()
	day15.Part2()

}
